fix pubovl being sent to everyone when changing team, remove typings …
VierEck/aos-scripts pull request #2
Opened 2022-09-17 00:23 UTC by DryByte

Fix script sending on chat every time you change team, the message of "you are no longer using pubovl".
Also i removed all variable types because not have a reason that be there, and added return to the function for script compatibility, since we dont return the original function other scripts thats lower in the hierarchy not will be able to use that function.

2022-09-19 19:20 UTC, VierEck requested changes
i have not much experience with all this so i wait before merging and comment the issues i had. 
thank you very much for ur efforts. i need more feedback from u on this since i dont have much experience.

2022-09-19 19:20 UTC, VierEck commented on pubovl.py
> +        def spawn(self, pos):
with this change i cant join the game with openspades. my console prints this out when this happens:
`TypeError: apply_script.<locals>.pubovlConnection.spawn() missing 1 required positional argument: 'pos'`

i reverted the change in 95/96 when testing which apparently solved this issue

2022-09-19 19:20 UTC, VierEck commented on pubovl.py
> +        def kill(self, by, kill_type, grenade):
with this change /kill doesnt work for me. console prints this out:
`TypeError: apply_script.<locals>.pubovlConnection.kill() missing 3 required positional arguments: 'by', 'kill_type', and 'grenade'`

i reverted this change in line 68/67 when testing which made /kill work again.

2022-09-19 19:20 UTC, VierEck commented on pubovl.py
> +            return connection.spawn(self, pos)
with this change, when ovl is activated, when u respawn after getting killed u also respawn client-side. this kicks u out of client-side spectator mode thus disrupting the ovl. this is very unpractical for moderating when u always have to do /ovl again and then select the player spectated before again after getting killed.

when testing i removed the function return which solved the issue for me. 

i havent used pique much yet and dont have any experience in coding in general so i dont know if function return is important. if no function return blocks other scripts from working as u said then that would render this entire script rather unpractical. 
Since i dont have much experience with all this though it would be helpful if i can get feedback from you on this issue.

2022-09-19 19:20 UTC, VierEck commented on pubovl.py
> +from pyspades.constants import WEAPON_TOOL
after changing some stuff to get this new version working, i reverted the change on line 67/68 thus i still needed to import WEAPON_KILL

2022-09-19 19:20 UTC, VierEck commented on pubovl.py
> +            return connection.on_team_changed(self, old_team)
this change line 147-152 works well! thank you very much <3

2022-09-20 00:01 UTC, DryByte commented
Now its supposed to work well, sorry for annoying you because this. I forgot that functions had default values in their parameters, and the last one i just didn't tested with multiple clients to perform a kill on me and check if a respawn happens. Thanks :D

2022-09-20 06:54 UTC, VierEck commented
its not annoying. im glad someone takes interest and helps me so much. thank you so much uw~~

2022-09-20 06:55 UTC, merged